
-- Clear existing sample data and insert comprehensive misdemeanors from knowledge base
DELETE FROM public.misdemeanors;

-- Insert Main School misdemeanors
INSERT INTO public.misdemeanors (id, location, name, sanctions, status, category, severity_level) VALUES
(gen_random_uuid(), 'Main School', 'Dropping Litter', '{"1st": "Picking up litter (15 minutes)"}', 'active', 'Maintenance', 1),
(gen_random_uuid(), 'Main School', 'Failing Haircut Check', '{"1st": "Manual Labour (1 hour 30 minutes) & withdrawal of phone privileges until hairstyle is correct"}', 'active', 'Appearance', 2),
(gen_random_uuid(), 'Main School', 'Unmarked Property', '{"1st": "Lines (1 page)"}', 'active', 'Organization', 1),
(gen_random_uuid(), 'Main School', 'Incorrect or Untidy Dress', '{"1st": "1 day of Dress inspection each", "2nd": "1 day of Dress inspection each", "3rd": "1 day of Dress inspection each", "4th": "1 hour manual labour", "5th": "1 hour 30 minutes manual labour", "6th": "Refer to Student Affairs"}', 'active', 'Dress Code', 2),
(gen_random_uuid(), 'Main School', 'Sharing of Clothing', '{"1st": "1 hour 30 minutes Manual Labour", "2nd": "2 hours Manual Labour and pupil writes a report emailed to parents"}', 'active', 'Dress Code', 2),
(gen_random_uuid(), 'Main School', 'Failure to Use Designated Pathways', '{"1st": "1 hour 30 minutes Manual Labour", "2nd": "2 hours Manual Labour"}', 'active', 'Rules', 2),
(gen_random_uuid(), 'Main School', 'Failure to Keep Locker Locked', '{"1st": "1 hour Manual Labour", "2nd": "1 hour 30 minutes Manual Labour and pupil writes a report to be emailed to parent"}', 'active', 'Security', 2),
(gen_random_uuid(), 'Main School', 'Improper Use of School Property', '{"1st": "1 hour 30 minutes Manual Labour", "2nd": "2 hours Manual Labour"}', 'active', 'Property', 2),
(gen_random_uuid(), 'Main School', 'Lateness to School (3 times)', '{"1st": "Manual Labour (30 minutes)", "2nd": "Additional 30 minutes for each subsequent offence", "3rd": "Additional 30 minutes for each subsequent offence", "4th": "Refer to Student Affairs"}', 'active', 'Punctuality', 3),
(gen_random_uuid(), 'Main School', 'Lateness to Class or Sport', '{"1st": "Reflection at 1:40pm for 15 minutes"}', 'active', 'Punctuality', 1),
(gen_random_uuid(), 'Main School', 'Bunking/Absenteeism', '{"1st": "7 hours 30 minutes Manual Labour", "2nd": "15 hours Manual Labour", "3rd": "22 hours 30 minutes Manual Labour", "4th": "Refer to Student Affairs"}', 'active', 'Attendance', 4),
(gen_random_uuid(), 'Main School', 'Out of Bounds', '{"1st": "Manual Labour (30 minutes)", "2nd": "Refer to Director Student Affairs"}', 'active', 'Location', 3),
(gen_random_uuid(), 'Main School', 'Exiting School Through Undesignated Exits', '{"1st": "Manual Labour (3 hours)", "2nd": "Refer to Director Student Affairs"}', 'active', 'Security', 4),
(gen_random_uuid(), 'Main School', 'Homework Not Done', '{"1st": "30 minutes Manual Labour", "2nd": "1 hour 30 minutes Manual Labour", "3rd": "3 hours Manual Labour"}', 'active', 'Academic', 2),
(gen_random_uuid(), 'Main School', 'Disruption of Lessons', '{"1st": "Manual Labour (35 minutes)"}', 'active', 'Behavior', 2),
(gen_random_uuid(), 'Main School', 'Failure to Bring Stationery/Textbooks', '{"1st": "Manual Labour (35 minutes)"}', 'active', 'Academic', 1),
(gen_random_uuid(), 'Main School', 'Disobedience and Disrespect', '{"1st": "Manual Labour (1 hour 30 minutes)", "2nd": "Refer to Director Student Affairs"}', 'active', 'Behavior', 4),
(gen_random_uuid(), 'Main School', 'Uncleared Cellphones or Use at Wrong Times', '{"1st": "90 days confiscation & name on notice board", "2nd": "12 months confiscation, name on notice board, and meet the Head"}', 'active', 'Technology', 3),
(gen_random_uuid(), 'Main School', 'Lending/Borrowing Confiscated Gadgets', '{"1st": "90 days confiscation & name on notice board", "2nd": "12 months confiscation, name on notice board, and meet the Head"}', 'active', 'Technology', 3),
(gen_random_uuid(), 'Main School', 'Illegal Electronic Devices (Videos, CDs, iPods, etc.)', '{"1st": "90 days confiscation & name on notice board", "2nd": "12 months confiscation, name on notice board, and meet the Head"}', 'active', 'Technology', 3),
(gen_random_uuid(), 'Main School', 'Stealing of Gadget/Cell Phone', '{"1st": "6-24 hours Manual Labour", "2nd": "Refer to Student Affairs"}', 'active', 'Theft', 5),
(gen_random_uuid(), 'Main School', 'Hacking of Accounts/Passwords', '{"1st": "1 hour 30 minutes Manual Labour", "2nd": "Refer to Student Affairs"}', 'active', 'Technology', 3),
(gen_random_uuid(), 'Main School', 'Bad Language/Swearing/Rudeness', '{"1st": "Manual Labour (12 hours)"}', 'active', 'Behavior', 4),
(gen_random_uuid(), 'Main School', 'Bullying/Theft/Violent Behavior', '{"1st": "Suspension for 14 days + Manual Labour (12 hours)", "2nd": "Boarders: Exclusion from Hostel", "3rd": "Day Scholars: Additional Manual Labour"}', 'active', 'Violence', 5),
(gen_random_uuid(), 'Main School', 'Vandalism/Bringing College into Disrepute', '{"1st": "Suspension for 14 days + Replace damaged property"}', 'active', 'Property', 5),
(gen_random_uuid(), 'Main School', 'Drinking/Smoking/Substance Abuse', '{"1st": "Suspension for 14 days + Manual Labour (12 hours)", "2nd": "Locker ban for a term + Driving ban"}', 'active', 'Substance', 5);

-- Insert Hostel misdemeanors  
INSERT INTO public.misdemeanors (id, location, name, sanctions, status, category, severity_level) VALUES
(gen_random_uuid(), 'Hostel', 'Failure in Daily Dress Inspection', '{"1st": "1 day Dress inspection", "2nd": "1 day Dress inspection", "3rd": "1 day Dress inspection", "4th": "1 hour manual labour", "5th": "1 hour 30 minutes manual labour", "6th": "Refer to Hostel Parent"}', 'active', 'Dress Code', 2),
(gen_random_uuid(), 'Hostel', 'Cell Phone Misuse (Ringing/Charging During Restricted Times)', '{"1st": "6 weeks confiscation", "2nd": "1 term confiscation", "3rd": "1-year withdrawal"}', 'active', 'Technology', 3),
(gen_random_uuid(), 'Hostel', 'Destruction of Property/Vandalism', '{"1st": "Compensation + 2 hours manual labour + Warning", "2nd": "Compensation + 3 hours manual labour + Final Warning", "3rd": "Compensation + Exclusion from Hostel"}', 'active', 'Property', 4),
(gen_random_uuid(), 'Hostel', 'Unauthorized Use of Electrical Gadgets (Irons, Kettles)', '{"1st": "Confiscation for half term", "2nd": "Confiscation for full term", "3rd": "Confiscation for one academic year"}', 'active', 'Technology', 2),
(gen_random_uuid(), 'Hostel', 'Daily Inspections - Disorder in Locker/Unlocked', '{"1st": "30 minutes manual labour", "2nd": "30 minutes manual labour", "3rd": "30 minutes manual labour", "4th": "1 hour manual labour", "5th": "1 hour 30 minutes manual labour", "6th": "Refer to Hostel Parent"}', 'active', 'Organization', 1),
(gen_random_uuid(), 'Hostel', 'Daily Inspections - Bed Not Made Neatly', '{"1st": "30 minutes manual labour", "2nd": "30 minutes manual labour", "3rd": "30 minutes manual labour", "4th": "1 hour manual labour", "5th": "1 hour 30 minutes manual labour", "6th": "Refer to Hostel Parent"}', 'active', 'Maintenance', 1),
(gen_random_uuid(), 'Hostel', 'Daily Inspections - Assigned Floor Area Untidy', '{"1st": "30 minutes manual labour", "2nd": "30 minutes manual labour", "3rd": "30 minutes manual labour", "4th": "1 hour manual labour", "5th": "1 hour 30 minutes manual labour", "6th": "Refer to Hostel Parent"}', 'active', 'Maintenance', 1),
(gen_random_uuid(), 'Hostel', 'Daily Inspections - Late for Roll Call', '{"1st": "30 minutes manual labour", "2nd": "30 minutes manual labour", "3rd": "30 minutes manual labour", "4th": "1 hour manual labour", "5th": "1 hour 30 minutes manual labour", "6th": "Refer to Hostel Parent"}', 'active', 'Punctuality', 2),
(gen_random_uuid(), 'Hostel', 'Signing In/Out - Late', '{"1st": "Gated for three weekends"}', 'active', 'Rules', 2),
(gen_random_uuid(), 'Hostel', 'Signing In/Out - Not Signed', '{"1st": "Gated for three weekends + 3 hours manual labour"}', 'active', 'Rules', 3),
(gen_random_uuid(), 'Hostel', 'Signing In/Out - Unauthorized Person', '{"1st": "Gated for three weekends + 3 hours manual labour"}', 'active', 'Security', 3),
(gen_random_uuid(), 'Hostel', 'Signing In/Out - No Gate Pass', '{"1st": "Major Offence: Refer to Hostel Parent"}', 'active', 'Security', 4),
(gen_random_uuid(), 'Hostel', 'Staying at Hostel Outside Permitted Times', '{"1st": "1 hour 30 minutes manual labour", "2nd": "Refer to Hostel Parent"}', 'active', 'Rules', 2),
(gen_random_uuid(), 'Hostel', 'Disruption of Prep', '{"1st": "30 minutes manual labour", "2nd": "1 hour manual labour", "3rd": "Refer to Hostel Parent"}', 'active', 'Academic', 2),
(gen_random_uuid(), 'Hostel', 'Bunking Manual Labour', '{"1st": "Refer to Hostel Parent"}', 'active', 'Rules', 4),
(gen_random_uuid(), 'Hostel', 'Failure to Observe Rest Time', '{"1st": "35 minutes manual labour"}', 'active', 'Rules', 1),
(gen_random_uuid(), 'Hostel', 'Movement of Furniture Out of Dorms', '{"1st": "30 minutes manual labour", "2nd": "1 hour manual labour", "3rd": "Refer to Hostel Parent"}', 'active', 'Property', 2),
(gen_random_uuid(), 'Hostel', 'MP3/iPods (For Fm1-Fm3 Students)', '{"1st": "Confiscated for 6 weeks (then taken home)", "2nd": "Confiscated for full term", "3rd": "Confiscated for one academic year"}', 'active', 'Technology', 2),
(gen_random_uuid(), 'Hostel', 'Ear Pods/Headphones/PSPs (For All Students)', '{"1st": "Confiscated for 6 weeks", "2nd": "Confiscated for full term", "3rd": "Confiscation for one academic year"}', 'active', 'Technology', 2),
(gen_random_uuid(), 'Hostel', 'Loud Music in Car Park', '{"1st": "Verbal warning + 1 hour manual labour", "2nd": "Written warning + 2 hours manual labour", "3rd": "Vehicle banned from property"}', 'active', 'Noise', 2),
(gen_random_uuid(), 'Hostel', 'Hairdryers/Shavers Used After Stipulated Times', '{"1st": "30 minutes manual labour each time"}', 'active', 'Rules', 1),
(gen_random_uuid(), 'Hostel', 'Out of Bounds (Hostel)', '{"1st": "Gated for three weekends + 3 hours manual labour", "2nd": "Refer to Hostel Parent"}', 'active', 'Location', 3),
(gen_random_uuid(), 'Hostel', 'Pairing Off', '{"1st": "Verbal warning", "2nd": "1 hour manual labour", "3rd": "Refer to Hostel Parent"}', 'active', 'Behavior', 2),
(gen_random_uuid(), 'Hostel', 'Cutting Through Lawn by Juniors', '{"1st": "30 minutes manual labour", "2nd": "1 hour manual labour", "3rd": "Refer to Hostel Parent"}', 'active', 'Rules', 1),
(gen_random_uuid(), 'Hostel', 'Playing Ball Games in Prohibited Areas', '{"1st": "Ball confiscated for 3 weeks + 30 minutes manual labour + Compensation", "2nd": "Ball confiscated until end of term + 1 hour manual labour + Compensation", "3rd": "3 hours manual labour"}', 'active', 'Rules', 2),
(gen_random_uuid(), 'Hostel', 'Indecent Dressing', '{"1st": "Correct immediately + Verbal warning", "2nd": "Correct immediately + Report to Hostel Parent"}', 'active', 'Dress Code', 2),
(gen_random_uuid(), 'Hostel', 'Laundry Left Out After 9:00pm', '{"1st": "Check for clothing left for 2 days"}', 'active', 'Maintenance', 1),
(gen_random_uuid(), 'Hostel', 'Late to Dorm (15 Minutes Before Lights Out)', '{"1st": "Sweep the dorm the following morning"}', 'active', 'Punctuality', 1),
(gen_random_uuid(), 'Hostel', 'Polishing Shoes Indoors', '{"1st": "Clean up mess + Verbal warning", "2nd": "30 minutes manual labour", "3rd": "Refer to Hostel Parent"}', 'active', 'Maintenance', 1),
(gen_random_uuid(), 'Hostel', 'Unauthorized Use of Car (Passenger/Driver)', '{"1st": "1 hour manual labour", "2nd": "Refer to Hostel Parent"}', 'active', 'Transportation', 3),
(gen_random_uuid(), 'Hostel', 'Late for Meals', '{"1st": "Kitchen Duty"}', 'active', 'Punctuality', 1),
(gen_random_uuid(), 'Hostel', 'Excess Tuck', '{"1st": "Confiscation for 3 weeks + 30 minutes manual labour"}', 'active', 'Rules', 1),
(gen_random_uuid(), 'Hostel', 'Major Offences (Same as Main School)', '{"1st": "Refer to Hostel Director + Sanctions as per main school rules (Page 28)"}', 'active', 'Major', 5);
