// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajxzehsgroxpgfqnzlvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqeHplaHNncm94cGdmcW56bHZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODIxODAsImV4cCI6MjA2NTU1ODE4MH0.opUt5q0d1SdNs9Ss5TmCu4A1bZPvMsGedFArKot-lZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);